version: "3.1"
services:

    mysql57:
      image: mysql:5.7
      container_name: app-mysql57
      restart: always
      working_dir: /application
      volumes:
        - ../database/mysql57/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=123456
      ports:
        - "8083:3306"
