version: "3.1"
services:
    app-php71-fpm:
      build: ../phpdocker/php-71-fpm
      container_name: app-php71-fpm
      restart: always
      working_dir: /application
      volumes:
        - ../../:/application
        - ../phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
